apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels: 
      tier: worker
  template: 
    metadata:
      labels: 
        tier: worker
    spec:
      containers:
        - name: worker
          image: registry.gitlab.com/davycode/docker-registry/complex-docker-worker
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: '6379'